### ISSUE TITLE
NPE in ObjectStorageRequestExecutor.onResponse

### ISSUE THREAD

**Issue by vishna** [eyeem/mjolnir-android#6]
```java
java.lang.NullPointerException

       at com.eyeem.storage.Storage.retain(Storage.java:241)
       at com.eyeem.mjolnir.ObjectStorageRequestExecutor$2.onResponse(ObjectStorageRequestExecutor.java:37)
       at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5283)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by vishna** [comment]
after some thought, retaining null shouldn't crash storage thus:

https://github.com/eyeem/PotatoLibrary/issues/73
